# site.yml
---
- hosts: lampstack
  sudo: true
  roles:
    - bertvv.el7
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
- hosts: monitor
  sudo: true
  roles:
    - bertvv.el7
    - bertvv.collectd