# roles/ROLENAME/tasks/main.yml
---
# Before installing any new program, update your server
- name: upgrade all packages
  yum: name=* state=latest

# Download en unzip Siege en zet hem in de Home directory van de vagrant host.
- name: Download Siege
  get_url: url=http://download.joedog.org/siege/siege-3.1.0.tar.gz dest=/home/vagrant/ mode=0777
# unzippen
- unarchive: src=/home/vagrant/siege-3.1.0.tar.gz dest=/home/vagrant/ copy=no