# host_vars/lampstack.yml
---

el7_firewalld:
  - service: http
  - permanent: true
  - state: enabled

el7_firewall_allow_services:
  - http
  - https
  - ssh

httpd_scripting: 'php'

mariadb_databases:
  - wordpress

mariadb_users:
  - name: admin
    password: admin
    priv: 'wordpress.*:ALL'

mariadb_root_password: admin

wordpress_database: wordpress
wordpress_user: admin
wordpress_password: admin
