# host_vars/lampstack.yml
---

el7_repositories:
  - epel-release

el7_install_packages:
  - bash-completion
  - policycoreutils
  - setroubleshoot-server
  - tree
  - vim-enhanced

el7_firewall_allow_services:
  - http
  - https

httpd_scripting: 'php'

mariadb_databases:
  - wordpress

mariadb_users:
  - name: wordpressusr
    password: BulpashCod
    priv: 'wordpress.*:ALL'

mariadb_root_password: Teilvadci

wordpress_database: wordpress
wordpress_user: wordpressusr
wordpress_password: BulpashCod
