# host_vars/lampstack.yml
---
el7_firewalld:
  - service: http
  - permanent: true
  - state: enabled

el7_firewall_allow_services:
  - http
  - https
  - ssh

httpd_scripting: 'php'

mariadb_databases:
  - wordpress

mariadb_users:
  - name: wp_user
    password: root
    priv: 'wordpress.*:ALL'

mariadb_root_password: root

wordpress_database: wordpress
wordpress_user: wp_user
wordpress_password: root
