# host_vars/lampstack.yml
---

el7_firewall_allow_services:
  - http
  - https
  - ssh
el7_install_packages:
  - bash-completion
  - git
  - tree
  - vim
  - policycoreutils
  - setroubleshoot-server
el7_user_groups:
  - wheel
el7_repositories:
  - epel-release
el7_firewall_allow_ports:
  - 25826/udp

httpd_scripting: 'php'

mariadb_databases:
  - wordpress

mariadb_users:
  - name: wp_user
    password: test
    priv: 'wordpress.*:ALL'


mariadb_root_password: root

wordpress_database: wordpress
wordpress_user: wp_user
wordpress_password: test
wordpress_plugins:
  - name: wp-super-cache
    version: 1.4.5
  - name: demo-data-creator