# host_vars/pu004.yml
---
el7_firewalld:
  - service: http
  - permanent: true
  - state: enabled

el7_firewall_allow_services:
  - http
  - https
  - ssh

httpd_scripting: 'php'

mariadb_databases:
  - monitoring

mariadb_users:
  - name: admin
    password: admin
    priv: 'monitoring.*:ALL'

mariadb_root_password: root

wordpress_database: monitoring
wordpress_user: admin
wordpress_password: admin
wordpress_plugins:
  - name: wp-super-cache
    version: 1.4.5
  - name: demo-data-creator