# host_vars/monitor.yml
---
el7_firewall_allow_services:
  - http
  - https
  - ssh
el7_install_packages:
  - bash-completion
  - git
  - vim
  - tree
  - policycoreutils
  - setroubleshoot-server

el7_user_groups:
  - wheel
   
el7_repositories:
  - epel-release
el7_firewall_allow_ports:
  - 25826/udp
  
#ansible-role-siege-master_concurrent: 50